// Habit data for the Recovery habit analytics demo.
// Edit this file to change what habits render in the app.
window.HABIT_DATA = [
  {
    id: "hydration",
    title: "Drink 8 glasses of water",
    description: "Stay hydrated through the day to keep energy and focus up.",
    category: "Wellness",
    color: "#38bdf8",
    currentStreak: 6,
    bestStreak: 14,
    completedToday: false,
    history: [
      true, true, true, true, true, false, false,
      true, true, true, true, true, true, false,
      true, true, true, true, true, true, true,
    ],
  },
  {
    id: "sleep",
    title: "Sleep by 10:30 PM",
    description: "Protect recovery with a consistent, early sleep schedule.",
    category: "Recovery",
    color: "#a78bfa",
    currentStreak: 3,
    bestStreak: 9,
    completedToday: false,
    history: [
      false, true, true, true, false, false, false,
      true, true, true, true, true, false, false,
      true, true, true, false, true, true, true,
    ],
  },
  {
    id: "walk",
    title: "30-minute morning walk",
    description: "A gentle walk to clear the mind and build daily movement.",
    category: "Fitness",
    color: "#34d399",
    currentStreak: 4,
    bestStreak: 11,
    completedToday: false,
    history: [
      true, true, false, false, true, true, true,
      true, true, true, true, true, true, false,
      true, true, true, true, true, false, true,
    ],
  },
  {
    id: "meditation",
    title: "10-minute meditation",
    description: "Quiet the mind and practice presence before the day starts.",
    category: "Mindfulness",
    color: "#fbbf24",
    currentStreak: 2,
    bestStreak: 7,
    completedToday: false,
    history: [
      false, false, true, true, true, true, false,
      true, true, true, true, true, true, true,
      true, true, true, true, true, true, true,
    ],
  },
  {
    id: "no-caffeine",
    title: "No caffeine after 2 PM",
    description: "Cut afternoon caffeine to support deeper, more restful sleep.",
    category: "Recovery",
    color: "#fb7185",
    currentStreak: 8,
    bestStreak: 20,
    completedToday: false,
    history: [
      true, true, true, true, true, true, true,
      true, true, true, true, true, true, true,
      true, true, true, true, true, true, true,
    ],
  },
  {
    id: "journal",
    title: "Write a journal entry",
    description: "Reflect on the day's wins, struggles, and lessons learned.",
    category: "Mindfulness",
    color: "#2dd4bf",
    currentStreak: 1,
    bestStreak: 5,
    completedToday: false,
    history: [
      false, true, false, true, true, false, false,
      true, false, true, true, true, false, false,
      true, true, true, false, true, true, true,
    ],
  },
  {
    id: "strength",
    title: "Bodyweight strength session",
    description: "Short, consistent strength work to rebuild physical foundation.",
    category: "Fitness",
    color: "#f472b6",
    currentStreak: 3,
    bestStreak: 8,
    completedToday: false,
    history: [
      true, false, false, true, true, false, true,
      true, true, false, true, true, true, false,
      true, true, true, false, true, true, true,
    ],
  },
  {
    id: "sunlight",
    title: "15 minutes of sunlight",
    description: "Morning daylight to regulate mood, sleep, and energy rhythms.",
    category: "Wellness",
    color: "#facc15",
    currentStreak: 5,
    bestStreak: 13,
    completedToday: false,
    history: [
      true, true, true, true, true, false, true,
      true, true, true, true, true, true, true,
      true, true, true, true, true, true, true,
    ],
  },
  {
    id: "social",
    title: "Reach out to a friend",
    description: "Nurture the relationships that support long-term recovery.",
    category: "Connection",
    color: "#60a5fa",
    currentStreak: 1,
    bestStreak: 4,
    completedToday: false,
    history: [
      false, false, true, true, false, true, false,
      true, false, true, true, true, false, true,
      false, true, true, true, false, true, true,
    ],
  },
];